import { api } from "@/../convex/_generated/api";
import { useMutation, useQuery } from "convex/react";
import { router, useLocalSearchParams } from "expo-router";
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from "react-native";
import { Avatar, Button, Card, EmptyState, LoadingState, PageHeader, SectionHeader } from "@/components/ui";
import { useToast } from "@/components/toast";
import { colors } from "@/constants/theme";
import { errorMessage } from "@/lib/errors";
import { formatMoney } from "@/lib/money";

export default function GroupScreen() {
  const { groupId } = useLocalSearchParams<{ groupId: string }>(); const data = useQuery(api.groups.detail, { groupId: groupId as any }); const removeGroup = useMutation(api.groups.remove);
  const { showToast } = useToast();
  if (data === undefined) return <LoadingState label="Balancing the group…" />;
  if (!data) return <EmptyState icon="?" title="Group not found" body="It may have been deleted." />;
  const names = new Map<string, string>(data.members.map((member: any) => [member._id, member.name]));
  function confirmDelete() { Alert.alert("Delete this group?", "Every expense, settlement, member, and receipt image will be permanently deleted.", [{ text: "Cancel", style: "cancel" }, { text: "Delete group", style: "destructive", onPress: () => void removeGroup({ groupId: groupId as any }).then(() => router.replace("/(tabs)/groups")).catch((err) => showToast(errorMessage(err))) }]); }
  return <View style={styles.page}><ScrollView contentContainerStyle={styles.content} showsVerticalScrollIndicator={false}><PageHeader eyebrow={`${data.members.filter((m: any) => !m.archived && m.membershipStatus !== "invited").length} members`} title={data.group.name} subtitle="USD · Net balances" />
    <View style={styles.actions}><Button label="Add expense" compact onPress={() => router.push({ pathname: "/group/[groupId]/expense", params: { groupId } })} /><Button label="Split receipt" compact variant="secondary" onPress={() => router.push({ pathname: "/group/[groupId]/receipt", params: { groupId } })} /></View>
    <Card style={styles.balanceCard}><SectionHeader title="Balances" action={<Pressable onPress={() => router.push({ pathname: "/group/[groupId]/members", params: { groupId } })}><Text style={styles.link}>Manage members</Text></Pressable>} />{data.balances.map((balance: any) => <View key={balance.memberId} style={styles.balanceRow}><Avatar name={balance.name} size={36} /><Text style={styles.memberName}>{balance.name}</Text><View style={styles.right}><Text style={[styles.balanceAmount, balance.amount < 0 ? styles.negative : styles.positive]}>{balance.amount === 0 ? "Settled" : formatMoney(Math.abs(balance.amount))}</Text><Text style={styles.caption}>{balance.amount < 0 ? "owes" : balance.amount > 0 ? "is owed" : "all clear"}</Text></View></View>)}</Card>
    <SectionHeader title="Who should pay whom" action={data.suggestions.length ? <Button label="Settle up" compact variant="secondary" onPress={() => router.push({ pathname: "/group/[groupId]/settle", params: { groupId } })} /> : undefined} />
    {!data.suggestions.length ? <Card><Text style={styles.settled}>✓ Everyone is settled up</Text></Card> : <View style={styles.suggestions}>{data.suggestions.map((item: any) => <Card key={`${item.fromMemberId}-${item.toMemberId}`} style={styles.suggestion}><Text style={styles.suggestionText}><Text style={styles.strong}>{item.fromName}</Text> pays <Text style={styles.strong}>{item.toName}</Text></Text><Text style={styles.suggestionAmount}>{formatMoney(item.amount)}</Text></Card>)}</View>}
    <SectionHeader title="Recent activity" />{!data.expenses.length && !data.settlements.length ? <EmptyState icon="🧾" title="No expenses yet" body="Add an expense or split a receipt to see balances." /> : <View style={styles.history}>{[...data.expenses.map((item: any) => ({ ...item, kind: "expense", when: item.date })), ...data.settlements.map((item: any) => ({ ...item, kind: "settlement", when: item.date }))].sort((a, b) => b.when - a.when).map((item: any) => item.kind === "expense" ? <Pressable key={`e-${item._id}`} onPress={() => router.push({ pathname: "/expense/[expenseId]", params: { expenseId: item._id } })}><Card style={styles.historyRow}><View style={styles.historyCopy}><Text style={styles.historyTitle}>{item.description}</Text><Text style={styles.meta}>{names.get(item.payerId)} paid · {new Date(item.date).toLocaleDateString()}</Text></View><Text style={styles.historyAmount}>{formatMoney(item.amount)}</Text></Card></Pressable> : <Card key={`s-${item._id}`} style={styles.historyRow}><View style={styles.historyCopy}><Text style={styles.historyTitle}>{names.get(item.fromMemberId)} paid {names.get(item.toMemberId)}</Text><Text style={styles.meta}>Settlement · {new Date(item.date).toLocaleDateString()}</Text></View><Text style={styles.historyAmount}>{formatMoney(item.amount)}</Text></Card>)}</View>}
    {data.isOwner ? <Button label="Delete group" variant="danger" onPress={confirmDelete} /> : null}
  </ScrollView></View>;
}
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: colors.background }, content: { flexGrow: 1, padding: 16, paddingBottom: 44, gap: 16 }, actions: { flexDirection: "row", gap: 10 }, balanceCard: { gap: 2 }, link: { color: colors.primary, fontWeight: "600", fontSize: 13 }, balanceRow: { flexDirection: "row", alignItems: "center", gap: 10, paddingVertical: 11, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.border }, memberName: { flex: 1, color: colors.ink, fontWeight: "600" }, right: { alignItems: "flex-end" }, balanceAmount: { fontWeight: "700" }, positive: { color: colors.positive }, negative: { color: colors.negative }, caption: { color: colors.inkMuted, fontSize: 11, marginTop: 2 }, suggestions: { gap: 9 }, suggestion: { flexDirection: "row", alignItems: "center", padding: 14 }, suggestionText: { flex: 1, color: colors.inkMuted }, strong: { color: colors.ink, fontWeight: "700" }, suggestionAmount: { color: colors.ink, fontWeight: "800", fontSize: 16 }, settled: { textAlign: "center", color: colors.positive, fontWeight: "700" }, history: { gap: 9 }, historyRow: { flexDirection: "row", alignItems: "center", padding: 14 }, historyCopy: { flex: 1, gap: 3 }, historyTitle: { color: colors.ink, fontWeight: "600" }, meta: { color: colors.inkMuted, fontSize: 12 }, historyAmount: { color: colors.ink, fontWeight: "700" } });
