import { api } from "@/../convex/_generated/api";
import { useMutation, useQuery } from "convex/react";
import { router, useLocalSearchParams } from "expo-router";
import { Alert, StyleSheet, Text, View } from "react-native";
import { useState } from "react";
import { Avatar, Button, Card, Field, LoadingState, PageHeader, SectionHeader, Screen } from "@/components/ui";
import { useToast } from "@/components/toast";
import { colors } from "@/constants/theme";
import { errorMessage } from "@/lib/errors";

export default function MembersScreen() {
  const { groupId } = useLocalSearchParams<{ groupId: string }>();
  const data = useQuery(api.groups.detail, { groupId: groupId as any });
  const invitations = useQuery(api.invitations.list, data?.isOwner ? { groupId: groupId as any } : "skip");
  const addGuest = useMutation(api.members.add); const createInvite = useMutation(api.invitations.create); const createGuestClaim = useMutation(api.invitations.createGuestClaim); const revoke = useMutation(api.invitations.revoke); const archive = useMutation(api.members.archive);
  const { showToast } = useToast(); const [guestName, setGuestName] = useState(""); const [inviteName, setInviteName] = useState(""); const [loading, setLoading] = useState<"guest" | "invite" | null>(null); const [newCode, setNewCode] = useState<{ name: string; code: string; expiresAt: number } | null>(null);
  if (data === undefined) return <LoadingState label="Loading members…" />;
  async function addGuestMember() { setLoading("guest"); try { await addGuest({ groupId: groupId as any, name: guestName }); setGuestName(""); showToast("Guest added to the group.", "success"); } catch (err) { showToast(errorMessage(err)); } finally { setLoading(null); } }
  async function inviteMember() { setLoading("invite"); try { const invite = await createInvite({ groupId: groupId as any, name: inviteName }); setInviteName(""); setNewCode({ name: inviteName.trim(), ...invite }); showToast("Invite code created. Share it with your friend.", "success"); } catch (err) { showToast(errorMessage(err)); } finally { setLoading(null); } }
  function remove(member: any) { Alert.alert(`Remove ${member.name}?`, "Members with financial history are archived so past expenses stay accurate.", [{ text: "Cancel", style: "cancel" }, { text: "Remove", style: "destructive", onPress: () => void archive({ memberId: member._id }).catch((err) => showToast(errorMessage(err))) }]); }
  async function makeClaimCode(member: any) { try { const invite = await createGuestClaim({ memberId: member._id }); setNewCode({ name: member.name, ...invite }); showToast("Claim code created. Only share it with this guest.", "success"); } catch (err) { showToast(errorMessage(err)); } }
  const memberStatus = (member: any) => member.archived ? "Archived" : member.membershipStatus === "invited" ? "Pending invite" : member.linkedClerkId ? "Registered" : "Guest";
  return <Screen><PageHeader title="Members" subtitle={data?.isOwner ? "Invite signed-in friends, or keep a guest for offline participants." : "Everyone in this shared group."} />
    {data?.isOwner ? <><Card style={styles.form}><SectionHeader title="Invite a friend" /><Text style={styles.helper}>They sign in or create an account, then enter the one-time code.</Text><Field label="Friend's name" value={inviteName} onChangeText={setInviteName} placeholder="Alex" autoCapitalize="words" maxLength={60} /><Button label="Create invite code" onPress={inviteMember} loading={loading === "invite"} disabled={!inviteName.trim()} /></Card><Card style={styles.form}><SectionHeader title="Add guest" /><Text style={styles.helper}>Guests appear in balances but cannot open this group until you issue a claim code.</Text><Field label="Guest name" value={guestName} onChangeText={setGuestName} placeholder="Taylor" autoCapitalize="words" maxLength={60} /><Button label="Add guest" variant="secondary" onPress={addGuestMember} loading={loading === "guest"} disabled={!guestName.trim()} /></Card>{newCode ? <Card style={styles.codeCard}><Text style={styles.codeTitle}>Code for {newCode.name}</Text><Text style={styles.code}>{newCode.code}</Text><Text style={styles.helper}>Expires {new Date(newCode.expiresAt).toLocaleDateString()}. Your friend can enter it from the Join a group screen.</Text><Button label="Done" compact variant="ghost" onPress={() => setNewCode(null)} /></Card> : null}{invitations?.length ? <View style={styles.pending}><SectionHeader title="Pending invitations" />{invitations.map((invite) => <Card key={invite._id} style={styles.row}><View style={styles.copy}><Text style={styles.name}>{invite.memberName}</Text><Text style={styles.meta}>Code {invite.code} · expires {new Date(invite.expiresAt).toLocaleDateString()}</Text></View><Button label="Revoke" compact variant="ghost" onPress={() => void revoke({ invitationId: invite._id }).catch((err) => showToast(errorMessage(err)))} /></Card>)}</View> : null}</> : null}
    <View style={styles.list}><SectionHeader title="People" />{data?.members.map((member: any) => <Card key={member._id} style={styles.row}><Avatar name={member.name} /><View style={styles.copy}><Text style={styles.name}>{member.name}</Text><Text style={styles.meta}>{memberStatus(member)}</Text></View>{data?.isOwner && !member.archived && !member.linkedClerkId ? <View style={styles.memberActions}>{member.membershipStatus !== "invited" ? <Button label="Claim" compact variant="ghost" onPress={() => void makeClaimCode(member)} /> : null}<Button label="Remove" compact variant="ghost" onPress={() => remove(member)} /></View> : null}</Card>)}</View><Button label="Join a group with a code" variant="secondary" onPress={() => router.push("/invite")} />
  </Screen>;
}
const styles = StyleSheet.create({ form: { gap: 12 }, helper: { color: colors.inkMuted, fontSize: 13, lineHeight: 18 }, codeCard: { gap: 9, backgroundColor: colors.primarySoft }, codeTitle: { color: colors.ink, fontWeight: "700" }, code: { color: colors.primary, fontSize: 22, letterSpacing: 2, fontWeight: "800" }, pending: { gap: 9 }, list: { gap: 9 }, row: { flexDirection: "row", alignItems: "center", padding: 13 }, copy: { flex: 1, marginLeft: 11 }, name: { color: colors.ink, fontWeight: "600" }, meta: { color: colors.inkMuted, fontSize: 12, marginTop: 3 }, memberActions: { flexDirection: "row", alignItems: "center" } });
