import { api } from "@/../convex/_generated/api";
import { useMutation, useQuery } from "convex/react";
import * as ImagePicker from "expo-image-picker";
import { router, useLocalSearchParams } from "expo-router";
import { useEffect, useMemo, useRef, useState } from "react";
import { Alert, Image, Pressable, StyleSheet, Text, View } from "react-native";
import { Button, Card, Chip, ErrorBanner, Field, LoadingState, PageHeader, Screen, SectionHeader } from "@/components/ui";
import { colors } from "@/constants/theme";
import { errorMessage } from "@/lib/errors";
import { formatMoney, moneyInput, parseMoney } from "@/lib/money";

type DraftItem = { key: string; name: string; price: string; assigneeIds: string[] };
export default function ReceiptScreen() {
  const { groupId, expenseId } = useLocalSearchParams<{ groupId: string; expenseId?: string }>(); const group = useQuery(api.groups.detail, { groupId }); const existing = useQuery(api.expenses.get, expenseId ? { expenseId } : "skip");
  const create = useMutation(api.expenses.create); const update = useMutation(api.expenses.update); const generateUploadUrl = useMutation(api.expenses.generateUploadUrl);
  const [description, setDescription] = useState(""); const [payerId, setPayerId] = useState(""); const [subtotal, setSubtotal] = useState(""); const [tax, setTax] = useState("0.00"); const [tip, setTip] = useState("0.00");
  const [items, setItems] = useState<DraftItem[]>([{ key: "item-1", name: "", price: "", assigneeIds: [] }]); const [imageUri, setImageUri] = useState<string | null>(null); const [existingStorageId, setExistingStorageId] = useState<string | undefined>();
  const [loading, setLoading] = useState(false); const [error, setError] = useState(""); const initialized = useRef(false); const activeMembers = useMemo(() => group?.members.filter((member: any) => !member.archived) ?? [], [group?.members]);
  // eslint-disable-next-line react-hooks/set-state-in-effect -- Hydrate the editable form once after its Convex query resolves.
  useEffect(() => { if (!group || initialized.current || (expenseId && existing === undefined)) return; initialized.current = true; if (existing?.expense) { const e = existing.expense; setDescription(e.description); setPayerId(e.payerId); setSubtotal(moneyInput(e.subtotal)); setTax(moneyInput(e.tax)); setTip(moneyInput(e.tip)); setExistingStorageId(e.receiptStorageId); setImageUri(existing.receiptUrl); setItems((e.items ?? []).map((item: any) => ({ key: item.key, name: item.name, price: moneyInput(item.amount), assigneeIds: item.assigneeIds }))); } else setPayerId(activeMembers[0]?._id ?? ""); }, [activeMembers, existing, expenseId, group]);
  if (group === undefined || (expenseId && existing === undefined)) return <LoadingState label="Preparing receipt…" />;
  function chooseSource() { Alert.alert("Add receipt photo", undefined, [{ text: "Take photo", onPress: () => void takePhoto() }, { text: "Choose from library", onPress: () => void pickPhoto() }, { text: "Cancel", style: "cancel" }]); }
  async function takePhoto() { const permission = await ImagePicker.requestCameraPermissionsAsync(); if (!permission.granted) return Alert.alert("Camera access needed", "Allow camera access in Settings to photograph a receipt."); const result = await ImagePicker.launchCameraAsync({ mediaTypes: ["images"], quality: 0.65, allowsEditing: true }); if (!result.canceled) setImageUri(result.assets[0].uri); }
  async function pickPhoto() { const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ["images"], quality: 0.65, allowsEditing: true }); if (!result.canceled) setImageUri(result.assets[0].uri); }
  function patchItem(key: string, values: Partial<DraftItem>) { setItems((current) => current.map((item) => item.key === key ? { ...item, ...values } : item)); }
  function toggleAssignee(item: DraftItem, memberId: string) { patchItem(item.key, { assigneeIds: item.assigneeIds.includes(memberId) ? item.assigneeIds.filter((id) => id !== memberId) : [...item.assigneeIds, memberId] }); }
  const subtotalCents = parseMoney(subtotal) ?? 0, taxCents = parseMoney(tax) ?? 0, tipCents = parseMoney(tip) ?? 0, total = subtotalCents + taxCents + tipCents;
  async function uploadPhoto() { if (!imageUri || imageUri === existing?.receiptUrl) return existingStorageId; const uploadUrl = await generateUploadUrl({ groupId }); const blob = await (await fetch(imageUri)).blob(); const result = await fetch(uploadUrl, { method: "POST", headers: { "Content-Type": blob.type || "image/jpeg" }, body: blob }); if (!result.ok) throw new Error("Receipt photo upload failed. Try again."); return (await result.json()).storageId as string; }
  async function submit() { setLoading(true); setError(""); try { const parsedItems = items.map((item) => ({ key: item.key, name: item.name, amount: parseMoney(item.price) ?? 0, assigneeIds: item.assigneeIds })); const storageId = await uploadPhoto(); const values = { groupId, description, amount: total, payerId, splitType: "receipt" as const, date: existing?.expense.date ?? Date.now(), receiptStorageId: storageId, subtotal: subtotalCents, tax: taxCents, tip: tipCents, items: parsedItems }; if (expenseId) await update({ expenseId, ...values }); else await create(values); router.back(); } catch (err) { setError(errorMessage(err)); } finally { setLoading(false); } }
  return <Screen><PageHeader title={expenseId ? "Edit receipt" : "Split a receipt"} subtitle="Add each item, then assign who shared it." />{error ? <ErrorBanner message={error} /> : null}<Pressable onPress={chooseSource} style={styles.photo}>{imageUri ? <Image source={{ uri: imageUri }} style={styles.image} /> : <><Text style={styles.camera}>📷</Text><Text style={styles.photoTitle}>Add receipt photo</Text><Text style={styles.photoBody}>Camera or photo library</Text></>}</Pressable><Card style={styles.form}><Field label="Expense name" value={description} onChangeText={setDescription} placeholder="Dinner at Loro" maxLength={100} /><Text style={styles.label}>Who paid?</Text><View style={styles.chips}>{activeMembers.map((member: any) => <Chip key={member._id} label={member.name} selected={payerId === member._id} onPress={() => setPayerId(member._id)} />)}</View></Card>
    <SectionHeader title="Receipt totals" /><Card style={styles.form}><Field label="Subtotal" value={subtotal} onChangeText={setSubtotal} keyboardType="decimal-pad" placeholder="0.00" /><View style={styles.two}><View style={styles.flex}><Field label="Tax" value={tax} onChangeText={setTax} keyboardType="decimal-pad" /></View><View style={styles.flex}><Field label="Tip" value={tip} onChangeText={setTip} keyboardType="decimal-pad" /></View></View><View style={styles.totalRow}><Text style={styles.totalLabel}>Receipt total</Text><Text style={styles.totalAmount}>{formatMoney(total)}</Text></View></Card>
    <SectionHeader title="Items" action={<Button label="＋ Item" compact variant="secondary" onPress={() => setItems((current) => [...current, { key: `item-${Date.now()}`, name: "", price: "", assigneeIds: [] }])} />} />
    {items.map((item, index) => <Card key={item.key} style={styles.form}><View style={styles.itemHeader}><Text style={styles.itemTitle}>Item {index + 1}</Text>{items.length > 1 ? <Text style={styles.remove} onPress={() => setItems((current) => current.filter((entry) => entry.key !== item.key))}>Remove</Text> : null}</View><Field label="Item name" value={item.name} onChangeText={(name) => patchItem(item.key, { name })} placeholder="Tacos" /><Field label="Price" value={item.price} onChangeText={(price) => patchItem(item.key, { price })} keyboardType="decimal-pad" placeholder="0.00" /><Text style={styles.label}>Who had this?</Text><View style={styles.chips}>{activeMembers.map((member: any) => <Chip key={member._id} label={member.name} selected={item.assigneeIds.includes(member._id)} onPress={() => toggleAssignee(item, member._id)} />)}</View></Card>)}
    <Button label={expenseId ? "Save receipt" : "Add receipt expense"} onPress={submit} loading={loading} disabled={!description.trim() || !payerId || !subtotal || !items.length} />
  </Screen>;
}
const styles = StyleSheet.create({ photo: { minHeight: 150, borderWidth: 1, borderStyle: "dashed", borderColor: colors.border, borderRadius: 16, alignItems: "center", justifyContent: "center", overflow: "hidden", backgroundColor: colors.surface }, image: { width: "100%", height: 210, resizeMode: "cover" }, camera: { fontSize: 28 }, photoTitle: { color: colors.ink, fontWeight: "700", marginTop: 8 }, photoBody: { color: colors.inkMuted, fontSize: 12, marginTop: 3 }, form: { gap: 13 }, label: { color: colors.ink, fontSize: 14, fontWeight: "600" }, chips: { flexDirection: "row", flexWrap: "wrap", gap: 8 }, two: { flexDirection: "row", gap: 12 }, flex: { flex: 1 }, totalRow: { paddingTop: 12, borderTopWidth: 1, borderTopColor: colors.border, flexDirection: "row", justifyContent: "space-between" }, totalLabel: { color: colors.ink, fontWeight: "600" }, totalAmount: { color: colors.primary, fontWeight: "800", fontSize: 18 }, itemHeader: { flexDirection: "row", justifyContent: "space-between" }, itemTitle: { color: colors.ink, fontWeight: "700", fontSize: 16 }, remove: { color: colors.negative, fontWeight: "600" } });
